dotfiles = [
    ".bash_profile",
    ".bashrc",
    ".vimrc",
    ".alacritty.yml",
    ".gitconfig",
    ".tmux.conf",
    ".muttrc",
    ".gnupg/gpg.conf",
    ".config/procps/toprc",
]

target = "/home/bsa/dotfiles_linux"
keep_original_target = false
