dotfiles = [
    ".bash_profile",
    ".bashrc",
    ".vimrc",
    ".alacritty.yml",
    ".gitconfig",
    ".tmux.conf",
    ".muttrc"
]

target = "/home/bsa/dotfiles_linux"
keep_original_target = false
